---
steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--tag=gcr.io/${PROJECT_ID}/arachni'
  - '--file=arachni/Dockerfile'
  - '.'
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '--tag=gcr.io/${PROJECT_ID}/beef'
    - '--file=beef/Dockerfile'
    - '.'
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '--tag=gcr.io/${PROJECT_ID}/cewl'
    - '--file=cewl/Dockerfile'
    - '.'
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '--tag=gcr.io/${PROJECT_ID}/dirhunt'
    - '--file=dirhunt/Dockerfile'
    - '.'
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '--tag=gcr.io/${PROJECT_ID}/enum4linux'
    - '--file=enum4linux/Dockerfile'
    - '.'
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '--tag=gcr.io/${PROJECT_ID}/gobuster'
    - '--file=gobuster/Dockerfile'
    - '.'
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '--tag=gcr.io/${PROJECT_ID}/masscan'
    - '--file=masscan/Dockerfile'
    - '.'
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '--tag=gcr.io/${PROJECT_ID}/nbtscan'
    - '--file=nbtscan/Dockerfile'
    - '.'
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '--tag=gcr.io/${PROJECT_ID}/nikto'
    - '--file=nikto/Dockerfile'
    - '.'
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '--tag=gcr.io/${PROJECT_ID}/sqlmap'
    - '--file=sqlmap/Dockerfile'
    - '.'
images:
- 'gcr.io/${PROJECT_ID}/arachni:latest'
- 'gcr.io/${PROJECT_ID}/beef:latest'
- 'gcr.io/${PROJECT_ID}/cewl:latest'
- 'gcr.io/${PROJECT_ID}/dirhunt:latest'
- 'gcr.io/${PROJECT_ID}/enum4linux:latest'
- 'gcr.io/${PROJECT_ID}/gobuster:latest'
- 'gcr.io/${PROJECT_ID}/masscan:latest'
- 'gcr.io/${PROJECT_ID}/nbtscan:latest'
- 'gcr.io/${PROJECT_ID}/nikto:latest'
- 'gcr.io/${PROJECT_ID}/sqlmap:latest'
